@isTest
public with sharing class ParkLocatorTest {
	@isTest 
	static void testCallout() {              
        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new ParkServiceMock());
        // Call the method that invokes a callout
        List<String> result = ParkLocator.country('Alemanha');
        // Verify that a fake result is returned
        System.assertEquals(1, result.size()); 
    }
}
